# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.17.0
_src_path: gh:radio-aktywne/template-service-litestar
accountname: radio-aktywne
description: Broadcast streaming gate 🚧
docs: true
docsurl: https://radio-aktywne.github.io/octopus
email: it@radioaktywne.pl
envprefix: OCTOPUS
events: true
imagename: services/octopus
importname: octopus
port: 10300
registry: true
releases: true
reponame: octopus
repourl: https://github.com/radio-aktywne/octopus
servicename: octopus
sse: true
